-- ============================================================
-- GEDWEY IGNASIA — EXTRA SPICY / MATURE GAME CARDS
-- Safe to run on existing DB — INSERT only, does NOT delete rows
-- Requires: game_cards table (from full-setup.sql or seed-game-cards.sql)
-- Run after: seed-game-cards-data.sql (optional but recommended)
-- ============================================================

INSERT INTO game_cards (game_type, category, prompt, option_a, option_b, is_dare, age_gate) VALUES

-- ── TRUTH OR DARE (mature) ──────────────────────────────────
('truth_or_dare','mature','What scent, outfit, or look of mine instantly shifts your mood toward intimacy?',NULL,NULL,false,true),
('truth_or_dare','mature','When do you feel most confident initiating closeness with me?',NULL,NULL,false,true),
('truth_or_dare','mature','What is a slow-burn moment — not rushed — that you wish we had more of?',NULL,NULL,false,true),
('truth_or_dare','mature','What is something I do in public that secretly makes you want to be alone with me later?',NULL,NULL,false,true),
('truth_or_dare','mature','What type of kiss from me do you crave most: soft, deep, playful, or surprising?',NULL,NULL,false,true),
('truth_or_dare','mature','What is a boundary that actually makes you feel freer with me, not restricted?',NULL,NULL,false,true),
('truth_or_dare','mature','What song would you put on if you were setting the mood for us tonight?',NULL,NULL,false,true),
('truth_or_dare','mature','What is the most romantic thing I have done that still lives in your body when you think about it?',NULL,NULL,false,true),
('truth_or_dare','mature','What do you want me to understand about your desire that I might be missing?',NULL,NULL,false,true),
('truth_or_dare','mature','What is a compliment about your body that you want to hear more often?',NULL,NULL,false,true),
('truth_or_dare','mature','What does "being wanted" feel like to you — and when do I make you feel it most?',NULL,NULL,false,true),
('truth_or_dare','mature','What is a fantasy that stays playful and respectful — something we could talk through first?',NULL,NULL,false,true),
('truth_or_dare','mature','What is your favourite way to transition from an ordinary day into an intimate night together?',NULL,NULL,false,true),
('truth_or_dare','mature','What is something you loved in a past relationship that you have never asked me to try?',NULL,NULL,false,true),
('truth_or_dare','mature','What makes you feel sexy that has nothing to do with how you look?',NULL,NULL,false,true),
('truth_or_dare','mature','What is a place on your body that feels underrated — and wants more attention?',NULL,NULL,false,true),
('truth_or_dare','mature','What is the hottest non-physical thing I do: a glance, a text, a tone of voice?',NULL,NULL,false,true),
('truth_or_dare','mature','What would "perfect pacing" look like for us on a date that ends at home?',NULL,NULL,false,true),
('truth_or_dare','mature','What is one thing you want to hear me say before we get close?',NULL,NULL,false,true),
('truth_or_dare','mature','What is one thing you want to hear me say after we are close?',NULL,NULL,false,true),
('truth_or_dare','mature','What role does laughter play in intimacy for you — do we get it right?',NULL,NULL,false,true),
('truth_or_dare','mature','What is a gentle dare you have always wanted to give me but held back?',NULL,NULL,false,true),
('truth_or_dare','mature','What is your love language in the bedroom — words, touch, time, acts, or gifts?',NULL,NULL,false,true),
('truth_or_dare','mature','What is something you want to teach me about what feels good for you?',NULL,NULL,false,true),
('truth_or_dare','mature','What is something you want to learn from me about what feels good for me?',NULL,NULL,false,true),
('truth_or_dare','mature','Blindfold yourself for 30 seconds. Let your partner guide your hands to where they want to be touched.',NULL,NULL,true,true),
('truth_or_dare','mature','Pick a spot on your partner''s body and kiss it like it is the only place that matters.',NULL,NULL,true,true),
('truth_or_dare','mature','Describe out loud — in detail — the kiss you want next. Then give it.',NULL,NULL,true,true),
('truth_or_dare','mature','Trade places: you sit still, your partner explores your shoulders and neck for 45 seconds.',NULL,NULL,true,true),
('truth_or_dare','mature','Send your partner a voice note describing one thing you want to do later tonight.',NULL,NULL,true,true),
('truth_or_dare','mature','Slow dance with no music for one full song-length — at least 90 seconds.',NULL,NULL,true,true),
('truth_or_dare','mature','Look your partner in the eyes and say three specific things you find irresistible about them.',NULL,NULL,true,true),
('truth_or_dare','mature','Let your partner choose a playlist; you must stay close until the second song ends.',NULL,NULL,true,true),
('truth_or_dare','mature','Write one sentence on your partner''s skin with your finger — they guess the word.',NULL,NULL,true,true),
('truth_or_dare','mature','Give your partner a compliment they have never heard from you before — about desire, not just love.',NULL,NULL,true,true),
('truth_or_dare','mature','Ask your partner: "What would make you feel adored right now?" — then do it.',NULL,NULL,true,true),
('truth_or_dare','mature','Hold your partner from behind for 60 seconds — no phones, no talking.',NULL,NULL,true,true),
('truth_or_dare','mature','Plan out loud a "perfect hour" for just the two of you tonight — be specific.',NULL,NULL,true,true),
('truth_or_dare','mature','Let your partner pick a spot for a 10-second kiss. No negotiating.',NULL,NULL,true,true),
('truth_or_dare','mature','Whisper the first word that comes to mind when you think about your partner''s touch.',NULL,NULL,true,true),

-- ── WOULD YOU RATHER (mature) ───────────────────────────────
('would_you_rather','mature','Would you rather intimacy start with a long conversation or jump straight to touch?','Long talk first','Touch first',false,true),
('would_you_rather','mature','Would you rather the lights on or off?','Lights on','Lights off',false,true),
('would_you_rather','mature','Would you rather plan a romantic night or be surprised?','Plan together','Be surprised',false,true),
('would_you_rather','mature','Would you rather morning intimacy or late-night intimacy?','Morning','Late night',false,true),
('would_you_rather','mature','Would you rather receive a flirty text or a flirty voice note?','Text','Voice note',false,true),
('would_you_rather','mature','Would you rather a slow massage or a playful tickle fight that turns tender?','Slow massage','Playful tickle fight',false,true),
('would_you_rather','mature','Would you rather revisit your favourite memory together or create a brand-new one tonight?','Favourite memory','Brand-new moment',false,true),
('would_you_rather','mature','Would you rather cuddling for an hour or one intense 15-minute connection?','Hour of cuddling','15 intense minutes',false,true),
('would_you_rather','mature','Would you rather your partner initiate more or you initiate more this week?','Partner initiates','I initiate',false,true),
('would_you_rather','mature','Would you rather a stay-in date with candles or a hotel staycation?','Candles at home','Hotel staycation',false,true),
('would_you_rather','mature','Would you rather talk through fantasies together or keep some mystery?','Talk through','Keep mystery',false,true),
('would_you_rather','mature','Would you rather shower together or bath together?','Shower','Bath',false,true),
('would_you_rather','mature','Would you rather dress up for each other or dress down immediately?','Dress up','Dress down',false,true),
('would_you_rather','mature','Would you rather a week of teasing texts or a week of no phones when together?','Teasing texts','No phones together',false,true),
('would_you_rather','mature','Would you rather more spontaneity or more routine in intimacy?','Spontaneity','Routine',false,true),
('would_you_rather','mature','Would you rather receive a love letter or a curated playlist for the mood?','Love letter','Mood playlist',false,true),
('would_you_rather','mature','Would you rather kiss in the rain or stargaze wrapped in a blanket?','Kiss in rain','Stargaze wrapped up',false,true),
('would_you_rather','mature','Would you rather your partner whisper or speak clearly during intimate moments?','Whisper','Speak clearly',false,true),
('would_you_rather','mature','Would you rather explore something new together or perfect something you already love?','Something new','Perfect the familiar',false,true),
('would_you_rather','mature','Would you rather a romantic dinner out or cooking together in aprons?','Dinner out','Cook in aprons',false,true),
('would_you_rather','mature','Would you rather more eye contact or more playful distraction during foreplay?','Eye contact','Playful distraction',false,true),
('would_you_rather','mature','Would you rather a weekend with zero obligations or a single uninterrupted evening?','Free weekend','One perfect evening',false,true),
('would_you_rather','mature','Would you rather your partner read to you or you read to them — something romantic?','Partner reads','I read',false,true),
('would_you_rather','mature','Would you rather revisit the place you first kissed or never go back and make new places?','Revisit first kiss','New places only',false,true),
('would_you_rather','mature','Would you rather a soft playlist or complete silence when you are close?','Soft playlist','Complete silence',false,true),

-- ── THIS OR THAT (mature) ───────────────────────────────────
('this_or_that','mature','Pick your vibe tonight.','Slow burn','Playful energy',false,true),
('this_or_that','mature','What draws you in more right now?','A deep look','A teasing smile',false,true),
('this_or_that','mature','Choose your love language tonight.','Words','Touch',false,true),
('this_or_that','mature','What sounds better?','Candlelight','Morning light',false,true),
('this_or_that','mature','Which mood matches you?','Romantic','Passionate',false,true),
('this_or_that','mature','What feels more intimate?','Shared silence','Shared laughter',false,true),
('this_or_that','mature','Pick your preference.','Leading','Being led',false,true),
('this_or_that','mature','What is hotter?','Anticipation','Surprise',false,true),
('this_or_that','mature','Choose tonight''s pace.','Unhurried','Bold',false,true),
('this_or_that','mature','What connects you faster?','A long hug','A honest question',false,true),
('this_or_that','mature','Pick the setting.','Bedroom','Somewhere new in the house',false,true),
('this_or_that','mature','What matters more tonight?','Feeling adored','Feeling desired',false,true),
('this_or_that','mature','Choose your soundtrack.','Slow R&B','No music',false,true),
('this_or_that','mature','What is more your style?','Flirty banter','Serious tenderness',false,true),
('this_or_that','mature','Pick the energy.','Cozy','Electric',false,true),
('this_or_that','mature','What would you pick?','Holding hands first','Kissing first',false,true),
('this_or_that','mature','Choose the compliment style.','About your mind','About your body',false,true),
('this_or_that','mature','What feels more romantic?','A planned date','A spontaneous detour home',false,true),
('this_or_that','mature','Pick your temperature.','Warm shower together','Cool sheets',false,true),
('this_or_that','mature','What is more you?','Morning texts','Late-night whispers',false,true),
('this_or_that','mature','Choose the gesture.','Forehead kiss','Hand on lower back',false,true),
('this_or_that','mature','What sounds better right now?','Five more minutes cuddling','Five more minutes kissing',false,true),
('this_or_that','mature','Pick the fantasy frame.','Staycation','Road trip with a motel stop',false,true),
('this_or_that','mature','What do you want more of?','Praise','Playfulness',false,true),
('this_or_that','mature','Choose the ending.','Fall asleep tangled','Stay up talking',false,true),

-- ── DEEP QUESTIONS (mature) ─────────────────────────────────
('deep_questions','mature','What does emotional safety look like for you right before physical intimacy?',NULL,NULL,false,true),
('deep_questions','mature','How has your idea of desire changed since we got together?',NULL,NULL,false,true),
('deep_questions','mature','What is something you need to feel respected during vulnerable moments?',NULL,NULL,false,true),
('deep_questions','mature','When have you felt most seen by me in an intimate context?',NULL,NULL,false,true),
('deep_questions','mature','What is a fear about intimacy that gets smaller when you share it with me?',NULL,NULL,false,true),
('deep_questions','mature','How do you want me to respond when you are not in the mood — without taking it personally?',NULL,NULL,false,true),
('deep_questions','mature','What does "good intimacy" mean to you beyond the physical act?',NULL,NULL,false,true),
('deep_questions','mature','What is a memory of us that still makes your body react when you think about it?',NULL,NULL,false,true),
('deep_questions','mature','How do stress and exhaustion affect your desire — and how can I support you?',NULL,NULL,false,true),
('deep_questions','mature','What is one thing you wish society talked about more honestly in long-term relationships?',NULL,NULL,false,true),
('deep_questions','mature','What makes you feel proud of our physical connection?',NULL,NULL,false,true),
('deep_questions','mature','What is a conversation about intimacy we should revisit as we grow?',NULL,NULL,false,true),
('deep_questions','mature','How do you want to be checked in with — before, during, or after closeness?',NULL,NULL,false,true),
('deep_questions','mature','What is something you appreciate about how I express desire that you have never said aloud?',NULL,NULL,false,true),
('deep_questions','mature','What would help us keep novelty without pressure?',NULL,NULL,false,true),
('deep_questions','mature','What is your relationship with initiating — easy, hard, or depends on the day?',NULL,NULL,false,true),
('deep_questions','mature','What is a moment you felt completely chosen by me — body and heart?',NULL,NULL,false,true),
('deep_questions','mature','How do you want us to handle mismatched desire with kindness?',NULL,NULL,false,true),
('deep_questions','mature','What is intimacy teaching you about yourself lately?',NULL,NULL,false,true),
('deep_questions','mature','What is one tradition we could start that keeps romance alive in small ways?',NULL,NULL,false,true),
('deep_questions','mature','What does trust feel like in your body when you are with me?',NULL,NULL,false,true),
('deep_questions','mature','What is something you want to unlearn about intimacy from past experiences?',NULL,NULL,false,true),
('deep_questions','mature','How can we make "not tonight" feel loving instead of rejecting?',NULL,NULL,false,true),
('deep_questions','mature','What is a dream for our intimacy six months from now?',NULL,NULL,false,true),
('deep_questions','mature','What do you want our intimacy to say about our relationship to each other?',NULL,NULL,false,true),

-- ── RAPID FIRE (mature) ─────────────────────────────────────
('rapid_fire','mature','Go: Soft or intense?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Tease or direct?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Neck or hands?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Initiate or wait?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Candle or dim lamp?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Compliment or touch?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Playlist or silence?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Shower or sheets?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Morning or midnight?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Eyes open or closed?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Talk more or less?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Slow or playful?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Hug first or kiss first?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Planned or spontaneous?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Flirt text or voice note?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Stay in or hotel?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Massage or dance?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Whisper or laugh?',NULL,NULL,false,true),
('rapid_fire','mature','Go: One long kiss or many short ones?',NULL,NULL,false,true),
('rapid_fire','mature','Go: Adored or desired — which do you need tonight?',NULL,NULL,false,true);

-- Added: 40 truth_or_dare + 25 would_you_rather + 25 this_or_that + 25 deep_questions + 20 rapid_fire = 135 rows
SELECT 'Inserted extra mature/spicy game cards. Enable Mature Mode in Settings to play.' AS status;
